### ISSUE TITLE
Post-run error

### ISSUE THREAD

**Issue by knightsg** [dw/mitogen#333]
Background: I previously had an issue document in https://github.com/dw/mitogen/issues/319 where ansible using mitogen would fail immediately after starting a playbook run. That was resolved, and it appeared to be working fine. When I successfully tested that fix, I was using a playbook that imports 4 roles of 4 - 15 tasks each.

Current issue: I tried to run ansible using mitogen against our site.yml playbook that imports a bunch (18) of other playbooks. When I run site.yml against the same server (using -l <hostname>), I get this error after the run completes:
```

ERROR! [pid 4766] 13:57:01.410645 E mitogen.ctx.local.4790: mitogen: <IoLogger stderr> crashed
Traceback (most recent call last):
  File "<stdin>", line 1778, in _call
  File "<stdin>", line 1556, in on_receive
  File "<stdin>", line 896, in read
  File "<stdin>", line 287, in io_op
OSError: [Errno 11] Resource temporarily unavailable
ERROR! [pid 4766] 13:57:01.445036 E mitogen.ctx.local.4790: mitogen: <IoLogger stdout> crashed
Traceback (most recent call last):
  File "<stdin>", line 1778, in _call
  File "<stdin>", line 1556, in on_receive
  File "<stdin>", line 896, in read
  File "<stdin>", line 287, in io_op
OSError: [Errno 11] Resource temporarily unavailable
```
It doesn't appear to cause any issues apart from the error, but I thought I should post it here nonetheless.
 
**Setup**
Controller
Uname: Linux XXXXXXXXXX 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux (Windows Subsystem for Link - WSL, which is currently running Ubuntu 16.04.5)

**Ansible:**
ansible 2.4.6.0 (stable-2.4 9d08bc8242) last updated 2018/07/16 11:49:56 (GMT -700)
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/ansible/lib/ansible
  executable location = /usr/local/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

Notes: Added 'strategy_plugins = /path/to/mitogen-0.2.1/ansible_mitogen/plugins/strategy' to defaults and ran ansible-playbook with 'ANSIBLE_STRATEGY=mitogen_linear' set.

**Host(s)**
Uname: Linux XXXXXXXXXXXXXXX 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.6

**Comment by rouge8** [comment]
I think this is fixed in 0.2.2. http://mitogen.readthedocs.io/en/stable/changelog.html#v0-2-2-2018-07-26

**Comment by knightsg** [comment]
Unfortunately it's still happening for me in the master branch (commit #898c06f1).

**Comment by dw** [comment]
Sorry for the delay -- been super busy :)  I'm betting this is basically an epoll manifestation of https://github.com/dw/mitogen/issues/320

The fix will be similar, however the epoll interface is totally different to kqueue, so I need some free time to properly investigate it.

There is an underlying root cause to both these bugs, the previous fix didn't find/fix it.

**Comment by knightsg** [comment]
No worries, and thanks for the reply. I'm not in any major rush to get this working.

**Comment by dw** [comment]
I've simply avoided shutdown() use on WSL for now. If the WSL bug ever gets fixed, I'll remove look at removing the workaround.

This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!

**Comment by knightsg** [comment]
I tried this out today and it's now working without any errors. Just thought I'd confirm the fix - thanks!
